services:
  app:
    build: .
    environment:
      DB_HOST: postgres
      DB_NAME: SCC
      DB_USER: AndreyDol
      DB_PASSWORD: 123456
      DB_PORT: 5432
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: AndreyDol
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: SCC
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - my_network

networks:
  my_network:

volumes:
  pgdata:
